export enum CalculatorButton {
  Percent,
  ClearEntry,
  Clear,
  Delete,
  Reciprocal,
  Square,
  SquareRoot,
  Divide,
  Seven,
  Eight,
  Nine,
  Multiply,
  Four,
  Five,
  Six,
  Subtract,
  One,
  Two,
  Three,
  Add,
  Negate,
  Zero,
  Decimal,
  Equals,
}

export const CalculatorButtonLabels: Record<CalculatorButton, string> = {
  [CalculatorButton.Percent]: '%',
  [CalculatorButton.ClearEntry]: 'CE',
  [CalculatorButton.Clear]: 'C',
  [CalculatorButton.Delete]: 'DEL',
  [CalculatorButton.Reciprocal]: '1/x',
  [CalculatorButton.Square]: 'x²',
  [CalculatorButton.SquareRoot]: '√x',
  [CalculatorButton.Divide]: '÷',
  [CalculatorButton.Seven]: '7',
  [CalculatorButton.Eight]: '8',
  [CalculatorButton.Nine]: '9',
  [CalculatorButton.Multiply]: '×',
  [CalculatorButton.Four]: '4',
  [CalculatorButton.Five]: '5',
  [CalculatorButton.Six]: '6',
  [CalculatorButton.Subtract]: '−',
  [CalculatorButton.One]: '1',
  [CalculatorButton.Two]: '2',
  [CalculatorButton.Three]: '3',
  [CalculatorButton.Add]: '+',
  [CalculatorButton.Negate]: '±',
  [CalculatorButton.Zero]: '0',
  [CalculatorButton.Decimal]: '.',
  [CalculatorButton.Equals]: '=',
};
